### ISSUE TITLE
Missing ./datafiles/commonvoice/commonvoice_19.0_en_train_track2.json.gz

### ISSUE THREAD

**Issue by Wataru-Nakata** [urgent-challenge/urgent2025_challenge#2]
Thank you for organizing this repo. The script is great.
However, I found that the `commonvoice_19.0_en_train_track2.json.gz` is missing.
As a result, dataprep for track2 won't run.
Can you fix this if possible?

**Comment by kohei0209** [comment]
Hi, thank you for reporting the issue.
I've added `commonvoice_19.0_en_train_track2.json.gz` and the script should work now.

However, due to the huge number of files, it will take some more time to finish uploading MLS to HF. 
It will be done in 24 hours but I'll let you know once I finish uploading them all.

I apologize for the inconvenience.

**Comment by kohei0209** [comment]
Sorry for the delay. Uploading MLS to HF is done and data preparation for track2 should work now.
I've also added a missing data file which is necessary to download MLS. Please reflect the latest commit to your local before restarting the data preparation.
Thanks again for pointing out the issue!

**Comment by Wataru-Nakata** [comment]
Thank you for your prompt response to this matter!! closing this issue
